name: Production Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"                  # v1.0.0
      - "v[0-9]+.[0-9]+.[0-9]+-[A-Za-z]+.[0-9]+" # v1.0.0-alpha.1

jobs:
  test:
    name: Test
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  release:
    name: Release Production
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ vars.DOCKER_PRODUCTION_IMAGE_NAME }}:${{ github.ref_name }}
            ${{ vars.DOCKER_PRODUCTION_IMAGE_NAME }}:latest

      - name: Set New Preview Release Name
        uses: dkershner6/vercel-set-env-action@v3
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.VERCEL_ORG_ID }}
          projectName: ${{ secrets.VERCEL_PROJECT_NAME }}
          envVariableKeys: RELEASE_NAME
        env:
          RELEASE_NAME: ${{ github.ref_name }}
          TARGET_RELEASE_NAME: production
          TYPE_RELEASE_NAME: plain

      - name: Generate Changelog
        id: changelog
        uses: ardalanamini/auto-changelog@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          default-commit-type: Other Changes
          release-name: ${{ github.ref_name }}

      - name: Determine Prerelease Flag
        id: prerelease
        run: |
          if [[ ${{ github.ref_name }} =~ (alpha|beta|rc|next|canary) ]]; then
            echo "is-prerelease=true" >> $GITHUB_OUTPUT
          else
            echo "is-prerelease=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: ${{ steps.prerelease.outputs.is-prerelease }}
          body: |
            # ğŸš€ Release Notes

            ğŸ”– **Tag:** [${{ github.ref_name }}](https://github.com/${{ github.repository }}/tree/${{ github.ref_name }})

            ğŸ³ **Docker Image:** [${{ github.repository }}:${{ github.ref_name }}](https://ghcr.io/${{ github.repository }}:${{ github.ref_name }})
            ```bash
            # get latest image
            docker pull ghcr.io/${{ github.repository }}:latest

            # get this specific image
            docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ```

            # ğŸ“ Changelog
            ${{ steps.changelog.outputs.changelog }}
